create extension if not exists "pgcrypto";

do $$
begin
  if not exists (select 1 from pg_type where typname = 'sport_type') then
    create type sport_type as enum ('collective', 'individual', 'culture');
  end if;
  if not exists (select 1 from pg_type where typname = 'stream_status') then
    create type stream_status as enum ('draft', 'live', 'ended');
  end if;
  if not exists (select 1 from pg_type where typname = 'stream_access') then
    create type stream_access as enum ('public', 'private');
  end if;
end $$;

create table if not exists public.sports (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null,
  sport_type sport_type not null,
  is_team_based boolean not null default false,
  gender_division text not null default 'mixed',
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_sports_name on public.sports (lower(name));
create unique index if not exists uq_sports_slug on public.sports (lower(slug));
create unique index if not exists uq_sports_slug_raw on public.sports (slug);
create index if not exists idx_sports_type_active on public.sports (sport_type, is_active);

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  sport_id uuid not null references public.sports(id) on delete cascade,
  name text not null,
  short_code text,
  city text,
  coach_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_teams_sport_name on public.teams (sport_id, lower(name));
create unique index if not exists uq_teams_sport_name_raw on public.teams (sport_id, name);
create index if not exists idx_teams_sport_id on public.teams (sport_id);

create table if not exists public.team_players (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  full_name text not null,
  position text,
  jersey_number integer,
  is_captain boolean not null default false,
  created_at timestamptz not null default now(),
  unique(team_id, full_name)
);

create index if not exists idx_team_players_team_id on public.team_players (team_id);

create table if not exists public.profile_roles (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role_name text not null,
  created_at timestamptz not null default now(),
  unique(profile_id, role_name)
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profile_roles_role_name_check'
      and conrelid = 'public.profile_roles'::regclass
  ) then
    alter table public.profile_roles
    add constraint profile_roles_role_name_check
    check (
      role_name in (
        'participant',
        'admin',
        'organizer',
        'referee',
        'judge',
        'media',
        'coach'
      )
    );
  end if;
end $$;

create index if not exists idx_profile_roles_profile on public.profile_roles (profile_id);
create index if not exists idx_profile_roles_role_name on public.profile_roles (role_name);

create table if not exists public.live_streams (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  event_id uuid references public.events(id) on delete set null,
  host_profile_id uuid references public.profiles(id) on delete set null,
  playback_url text,
  status stream_status not null default 'draft',
  access stream_access not null default 'public',
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_live_streams_status_started on public.live_streams (status, starts_at desc);
create index if not exists idx_live_streams_event on public.live_streams (event_id);
create index if not exists idx_live_streams_host on public.live_streams (host_profile_id);
create index if not exists idx_live_streams_public_live on public.live_streams (starts_at desc) where status = 'live' and access = 'public';

alter table public.profiles
  add column if not exists username text,
  add column if not exists phone text,
  add column if not exists bio text,
  add column if not exists avatar_url text,
  add column if not exists favorite_sports text[] not null default '{}',
  add column if not exists locale text not null default 'en',
  add column if not exists timezone text not null default 'Africa/Algiers',
  add column if not exists last_seen_at timestamptz;

create unique index if not exists uq_profiles_username on public.profiles (lower(username)) where username is not null;
create index if not exists idx_profiles_role on public.profiles (role);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_username_format_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
    add constraint profiles_username_format_check
    check (
      username is null or username ~ '^[a-zA-Z0-9_]{3,32}$'
    );
  end if;
end $$;

alter table public.events
  add column if not exists sport_id uuid references public.sports(id) on delete set null,
  add column if not exists registration_deadline timestamptz,
  add column if not exists max_participants integer,
  add column if not exists is_featured boolean not null default false,
  add column if not exists visibility text not null default 'public',
  add column if not exists banner_url text,
  add column if not exists is_registration_open boolean not null default true,
  add column if not exists current_round text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'events_visibility_check'
      and conrelid = 'public.events'::regclass
  ) then
    alter table public.events
    add constraint events_visibility_check
    check (visibility in ('public', 'private'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'events_max_participants_check'
      and conrelid = 'public.events'::regclass
  ) then
    alter table public.events
    add constraint events_max_participants_check
    check (max_participants is null or max_participants > 0);
  end if;
end $$;

create index if not exists idx_events_sport_status_start on public.events (sport_id, status, starts_at);
create index if not exists idx_events_registration_deadline on public.events (registration_deadline);

alter table public.matches
  add column if not exists team_a_id uuid references public.teams(id) on delete set null,
  add column if not exists team_b_id uuid references public.teams(id) on delete set null,
  add column if not exists event_phase text not null default 'group',
  add column if not exists mvp_player text,
  add column if not exists live_minute integer,
  add column if not exists is_prediction_locked boolean not null default false,
  add column if not exists winning_team_id uuid references public.teams(id) on delete set null,
  add column if not exists stream_id uuid references public.live_streams(id) on delete set null,
  add column if not exists notes text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'matches_live_minute_check'
      and conrelid = 'public.matches'::regclass
  ) then
    alter table public.matches
    add constraint matches_live_minute_check
    check (live_minute is null or live_minute >= 0);
  end if;
end $$;

create index if not exists idx_matches_event_status_start on public.matches (event_id, status, starts_at);
create index if not exists idx_matches_team_a_id on public.matches (team_a_id);
create index if not exists idx_matches_team_b_id on public.matches (team_b_id);
create index if not exists idx_matches_stream_id on public.matches (stream_id);
create unique index if not exists uq_matches_event_teams_start on public.matches (event_id, team_a, team_b, starts_at);

alter table public.registrations
  add column if not exists profile_id uuid references public.profiles(id) on delete set null,
  add column if not exists registration_code text,
  add column if not exists attendance_status text not null default 'pending',
  add column if not exists checked_in_at timestamptz,
  add column if not exists emergency_contact text;

update public.registrations
set registration_code = substring(replace(gen_random_uuid()::text, '-', ''), 1, 10)
where registration_code is null;

alter table public.registrations
  alter column registration_code set default substring(replace(gen_random_uuid()::text, '-', ''), 1, 10);

alter table public.registrations
  alter column registration_code set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'registrations_attendance_status_check'
      and conrelid = 'public.registrations'::regclass
  ) then
    alter table public.registrations
    add constraint registrations_attendance_status_check
    check (attendance_status in ('pending', 'checked_in', 'absent', 'cancelled'));
  end if;
end $$;

create unique index if not exists uq_registrations_code on public.registrations (registration_code);
create unique index if not exists uq_registrations_user_event on public.registrations (user_id, event_id) where user_id is not null;
create index if not exists idx_registrations_profile_status on public.registrations (profile_id, status, created_at desc);
create index if not exists idx_registrations_event_status on public.registrations (event_id, status);

alter table public.predictions
  add column if not exists predicted_score_a integer not null default 0,
  add column if not exists predicted_score_b integer not null default 0,
  add column if not exists predicted_mvp_player text,
  add column if not exists stake_points integer not null default 1,
  add column if not exists outcome text not null default 'pending',
  add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'predictions_scores_non_negative_check'
      and conrelid = 'public.predictions'::regclass
  ) then
    alter table public.predictions
    add constraint predictions_scores_non_negative_check
    check (predicted_score_a >= 0 and predicted_score_b >= 0);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'predictions_stake_points_check'
      and conrelid = 'public.predictions'::regclass
  ) then
    alter table public.predictions
    add constraint predictions_stake_points_check
    check (stake_points between 1 and 10);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'predictions_outcome_check'
      and conrelid = 'public.predictions'::regclass
  ) then
    alter table public.predictions
    add constraint predictions_outcome_check
    check (outcome in ('pending', 'won', 'lost'));
  end if;
end $$;

create index if not exists idx_predictions_user_created on public.predictions (user_id, created_at desc);
create index if not exists idx_predictions_match_points on public.predictions (match_id, points_awarded desc);
create unique index if not exists uq_results_event_participant_placement on public.results (event_id, participant_or_team_name, placement);

drop trigger if exists trg_sports_touch_updated_at on public.sports;
create trigger trg_sports_touch_updated_at
before update on public.sports
for each row execute procedure public.touch_updated_at();

drop trigger if exists trg_teams_touch_updated_at on public.teams;
create trigger trg_teams_touch_updated_at
before update on public.teams
for each row execute procedure public.touch_updated_at();

drop trigger if exists trg_live_streams_touch_updated_at on public.live_streams;
create trigger trg_live_streams_touch_updated_at
before update on public.live_streams
for each row execute procedure public.touch_updated_at();

drop trigger if exists trg_predictions_touch_updated_at on public.predictions;
create trigger trg_predictions_touch_updated_at
before update on public.predictions
for each row execute procedure public.touch_updated_at();

create or replace function public.is_staff(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.is_admin(uid)
    or exists (
      select 1
      from public.profile_roles pr
      where pr.profile_id = uid
        and pr.role_name in ('organizer', 'media', 'referee', 'judge', 'coach')
    );
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  role_value app_role := 'participant';
  role_label text := 'participant';
begin
  if exists (select 1 from public.admin_emails where email = lower(new.email)) then
    role_value := 'admin';
    role_label := 'admin';
  end if;

  insert into public.profiles (
    id,
    email,
    full_name,
    role,
    username,
    timezone
  )
  values (
    new.id,
    lower(coalesce(new.email, new.id::text || '@unknown.local')),
    coalesce(new.raw_user_meta_data->>'full_name', null),
    role_value,
    nullif(lower(new.raw_user_meta_data->>'username'), ''),
    coalesce(new.raw_user_meta_data->>'timezone', 'Africa/Algiers')
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = coalesce(excluded.full_name, public.profiles.full_name),
    role = excluded.role,
    username = coalesce(excluded.username, public.profiles.username),
    timezone = coalesce(excluded.timezone, public.profiles.timezone),
    updated_at = now();

  insert into public.profile_roles (profile_id, role_name)
  values (new.id, role_label)
  on conflict (profile_id, role_name) do nothing;

  return new;
end;
$$;

insert into public.profile_roles (profile_id, role_name)
select p.id,
  case when p.role = 'admin' then 'admin' else 'participant' end
from public.profiles p
on conflict (profile_id, role_name) do nothing;

alter table public.sports enable row level security;
alter table public.teams enable row level security;
alter table public.team_players enable row level security;
alter table public.profile_roles enable row level security;
alter table public.live_streams enable row level security;

drop policy if exists sports_public_read on public.sports;
create policy sports_public_read on public.sports
for select to anon, authenticated
using (is_active = true);

drop policy if exists sports_admin_manage on public.sports;
create policy sports_admin_manage on public.sports
for all to authenticated
using (public.is_admin((select auth.uid())))
with check (public.is_admin((select auth.uid())));

drop policy if exists teams_public_read on public.teams;
create policy teams_public_read on public.teams
for select to anon, authenticated
using (is_active = true);

drop policy if exists teams_admin_manage on public.teams;
create policy teams_admin_manage on public.teams
for all to authenticated
using (public.is_admin((select auth.uid())))
with check (public.is_admin((select auth.uid())));

drop policy if exists team_players_public_read on public.team_players;
create policy team_players_public_read on public.team_players
for select to anon, authenticated
using (true);

drop policy if exists team_players_admin_manage on public.team_players;
create policy team_players_admin_manage on public.team_players
for all to authenticated
using (public.is_admin((select auth.uid())))
with check (public.is_admin((select auth.uid())));

drop policy if exists profile_roles_read_own_or_admin on public.profile_roles;
create policy profile_roles_read_own_or_admin on public.profile_roles
for select to authenticated
using (
  profile_id = (select auth.uid())
  or public.is_admin((select auth.uid()))
);

drop policy if exists profile_roles_admin_manage on public.profile_roles;
create policy profile_roles_admin_manage on public.profile_roles
for all to authenticated
using (public.is_admin((select auth.uid())))
with check (public.is_admin((select auth.uid())));

drop policy if exists live_streams_public_read on public.live_streams;
create policy live_streams_public_read on public.live_streams
for select to anon, authenticated
using (
  access = 'public'
  or host_profile_id = (select auth.uid())
  or public.is_staff((select auth.uid()))
);

drop policy if exists live_streams_staff_manage on public.live_streams;
create policy live_streams_staff_manage on public.live_streams
for all to authenticated
using (public.is_staff((select auth.uid())))
with check (public.is_staff((select auth.uid())));

drop policy if exists events_public_read on public.events;
create policy events_public_read on public.events
for select to anon, authenticated
using (
  visibility = 'public'
  and status in ('scheduled', 'live', 'completed')
);

drop policy if exists registrations_public_insert on public.registrations;
drop policy if exists registrations_authenticated_insert on public.registrations;
create policy registrations_authenticated_insert on public.registrations
for insert to authenticated
with check (
  user_id = (select auth.uid())
  and profile_id = (select auth.uid())
);

drop policy if exists predictions_insert_own on public.predictions;
create policy predictions_insert_own on public.predictions
for insert to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.matches m
    where m.id = match_id
      and m.status <> 'completed'
      and m.is_prediction_locked = false
  )
);

drop policy if exists predictions_update_own_or_admin on public.predictions;
create policy predictions_update_own_or_admin on public.predictions
for update to authenticated
using (
  public.is_admin((select auth.uid()))
  or (
    user_id = (select auth.uid())
    and exists (
      select 1
      from public.matches m
      where m.id = match_id
        and m.status <> 'completed'
        and m.is_prediction_locked = false
    )
  )
)
with check (
  public.is_admin((select auth.uid()))
  or (
    user_id = (select auth.uid())
    and exists (
      select 1
      from public.matches m
      where m.id = match_id
        and m.status <> 'completed'
        and m.is_prediction_locked = false
    )
  )
);

insert into public.app_settings (key, value)
values
  ('live_streaming_enabled', 'true'::jsonb),
  ('registration_max_events_per_user', '8'::jsonb)
on conflict (key) do nothing;
